services:
  db:
    image: postgis/postgis:13-master
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    command: ["postgres", "-c", "log_statement=all"]

  db_manager:
    build:
      context: .
      dockerfile: lambdas/db_manager/db_manager.Dockerfile
    env_file:
      - .env
    environment:
      - DB_INSTANCE_ADDRESS=db
      - DB_INSTANCE_PORT=5432
      - READ_FROM_AWS=0
    ports:
      - "8081:8080"
    depends_on:
      - db
    volumes:
      - ./lambdas/db_manager/db_manager.py:/var/task/app.py

  koodistot_loader:
    build:
      context: .
      dockerfile: lambdas/koodistot_loader/koodistot_loader.Dockerfile
    env_file:
      - .env
    environment:
      - DB_INSTANCE_ADDRESS=db
      - DB_INSTANCE_PORT=5432
      - READ_FROM_AWS=0
    ports:
      - "8082:8080"
    depends_on:
      - db
    volumes:
      - ./lambdas/koodistot_loader/koodistot_loader.py:/var/task/app.py

  ryhti_client:
    build:
      context: .
      dockerfile: lambdas/ryhti_client/ryhti_client.Dockerfile
    env_file:
      - .env
    environment:
      - DB_INSTANCE_ADDRESS=db
      - DB_INSTANCE_PORT=5432
      - READ_FROM_AWS=0
      - SYKE_APIKEY
      - XROAD_HTTP_PORT=1080
      - XROAD_SERVER_ADDRESS=mock_xroad
      - XROAD_MEMBER_CLASS=COM
      - XROAD_MEMBER_CODE=2455538-5
      - XROAD_MEMBER_CLIENT_NAME=ryhti-gispo-client
      - XROAD_SYKE_CLIENT_ID=test-id
      - XROAD_SYKE_CLIENT_SECRET=test-secret
    ports:
      - "8083:8080"
    depends_on:
      - db
      - mock_xroad
    volumes:
      - ./lambdas/ryhti_client/ryhti_client.py:/var/task/app.py
      - ./ryhti_debug:/var/task/ryhti_debug

  mml_loader:
    build:
      context: .
      dockerfile: lambdas/mml_loader/mml_loader.Dockerfile
    env_file:
      - .env
    environment:
      - DB_INSTANCE_ADDRESS=db
      - DB_INSTANCE_PORT=5432
      - READ_FROM_AWS=0
      - MML_APIKEY
    ports:
      - "8085:8080"
    depends_on:
      - db
    volumes:
      - ./lambdas/mml_loader/mml_loader.py:/var/task/app.py

  mock_xroad:
      image: mockserver/mockserver:latest
      ports:
        - 8443:1080
      environment:
        - MOCKSERVER_WATCH_INITIALIZATION_JSON="true"
        - MOCKSERVER_PROPERTY_FILE=/config/mockserver.properties
        - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json
      volumes:
        - ./test/test_services_mock_xroad.json:/config/initializerJson.json:Z
