"""Edit plan regulation group table

Revision ID: 811b23178cef
Revises: c882368ce708
Create Date: 2024-02-08 14:23:00.747678

"""
from typing import Sequence, Union

# import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "811b23178cef"
down_revision: Union[str, None] = "c882368ce708"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan_regulation_group",
        sa.Column("exported_at", sa.DateTime(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_regulation_group",
        sa.Column("valid_from", sa.DateTime(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_regulation_group",
        sa.Column("valid_to", sa.DateTime(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_regulation_group",
        sa.Column("repealed_at", sa.DateTime(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_regulation_group",
        sa.Column("lifecycle_status_id", sa.UUID(), nullable=False),
        schema="hame",
    )
    op.create_foreign_key(
        "plan_lifecycle_status_id_fkey",
        "plan_regulation_group",
        "lifecycle_status",
        ["lifecycle_status_id"],
        ["id"],
        source_schema="hame",
        referent_schema="codes",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "plan_lifecycle_status_id_fkey",
        "plan_regulation_group",
        schema="hame",
        type_="foreignkey",
    )
    op.drop_column("plan_regulation_group", "lifecycle_status_id", schema="hame")
    op.drop_column("plan_regulation_group", "repealed_at", schema="hame")
    op.drop_column("plan_regulation_group", "valid_to", schema="hame")
    op.drop_column("plan_regulation_group", "valid_from", schema="hame")
    op.drop_column("plan_regulation_group", "exported_at", schema="hame")
    # ### end Alembic commands ###
