"""ordering index fixes

Revision ID: 09f44e0e7110
Revises: 4e3c0868ea98
Create Date: 2024-12-02 15:22:07.740316

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09f44e0e7110"
down_revision: Union[str, None] = "4e3c0868ea98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_hame_land_use_area_ordering",
        table_name="land_use_area",
        schema="hame",
    )
    op.create_index(
        "ix_land_use_area_plan_id_ordering",
        "land_use_area",
        ["plan_id", "ordering"],
        unique=True,
        schema="hame",
    )
    op.drop_index(
        "ix_hame_land_use_point_ordering",
        table_name="land_use_point",
        schema="hame",
    )
    op.create_index(
        "ix_land_use_point_plan_id_ordering",
        "land_use_point",
        ["plan_id", "ordering"],
        unique=True,
        schema="hame",
    )
    op.drop_index("ix_hame_line_ordering", table_name="line", schema="hame")
    op.create_index(
        "ix_line_plan_id_ordering",
        "line",
        ["plan_id", "ordering"],
        unique=True,
        schema="hame",
    )
    op.drop_index("ix_hame_other_area_ordering", table_name="other_area", schema="hame")
    op.create_index(
        "ix_other_area_plan_id_ordering",
        "other_area",
        ["plan_id", "ordering"],
        unique=True,
        schema="hame",
    )
    op.drop_index(
        "ix_hame_other_point_ordering", table_name="other_point", schema="hame"
    )
    op.create_index(
        "ix_other_point_plan_id_ordering",
        "other_point",
        ["plan_id", "ordering"],
        unique=True,
        schema="hame",
    )
    op.drop_index(
        "ix_hame_plan_proposition_ordering",
        table_name="plan_proposition",
        schema="hame",
    )
    op.create_index(
        "ix_plan_proposition_plan_regulation_group_id_ordering",
        "plan_proposition",
        ["plan_regulation_group_id", "ordering"],
        unique=True,
        schema="hame",
    )
    op.drop_index(
        "ix_hame_plan_regulation_ordering",
        table_name="plan_regulation",
        schema="hame",
    )
    op.create_index(
        "ix_plan_regulation_plan_regulation_group_id_ordering",
        "plan_regulation",
        ["plan_regulation_group_id", "ordering"],
        unique=True,
        schema="hame",
    )
    op.drop_index(
        "ix_hame_plan_regulation_group_ordering",
        table_name="plan_regulation_group",
        schema="hame",
    )
    op.create_index(
        "ix_plan_regulation_group_plan_id_ordering",
        "plan_regulation_group",
        ["plan_id", "ordering"],
        unique=False,
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_plan_regulation_group_plan_id_ordering",
        table_name="plan_regulation_group",
        schema="hame",
    )
    op.create_index(
        "ix_hame_plan_regulation_group_ordering",
        "plan_regulation_group",
        ["ordering"],
        unique=False,
        schema="hame",
    )
    op.drop_index(
        "ix_plan_regulation_plan_regulation_group_id_ordering",
        table_name="plan_regulation",
        schema="hame",
    )
    op.create_index(
        "ix_hame_plan_regulation_ordering",
        "plan_regulation",
        ["ordering"],
        unique=False,
        schema="hame",
    )
    op.drop_index(
        "ix_plan_proposition_plan_regulation_group_id_ordering",
        table_name="plan_proposition",
        schema="hame",
    )
    op.create_index(
        "ix_hame_plan_proposition_ordering",
        "plan_proposition",
        ["ordering"],
        unique=False,
        schema="hame",
    )
    op.drop_index(
        "ix_other_point_plan_id_ordering",
        table_name="other_point",
        schema="hame",
    )
    op.create_index(
        "ix_hame_other_point_ordering",
        "other_point",
        ["ordering"],
        unique=False,
        schema="hame",
    )
    op.drop_index(
        "ix_other_area_plan_id_ordering",
        table_name="other_area",
        schema="hame",
    )
    op.create_index(
        "ix_hame_other_area_ordering",
        "other_area",
        ["ordering"],
        unique=False,
        schema="hame",
    )
    op.drop_index("ix_line_plan_id_ordering", table_name="line", schema="hame")
    op.create_index(
        "ix_hame_line_ordering",
        "line",
        ["ordering"],
        unique=False,
        schema="hame",
    )
    op.drop_index(
        "ix_land_use_point_plan_id_ordering",
        table_name="land_use_point",
        schema="hame",
    )
    op.create_index(
        "ix_hame_land_use_point_ordering",
        "land_use_point",
        ["ordering"],
        unique=False,
        schema="hame",
    )
    op.drop_index(
        "ix_land_use_area_plan_id_ordering",
        table_name="land_use_area",
        schema="hame",
    )
    op.create_index(
        "ix_hame_land_use_area_ordering",
        "land_use_area",
        ["ordering"],
        unique=False,
        schema="hame",
    )
    # ### end Alembic commands ###
