"""add kuntajako

Revision ID: 3527051d7f9b
Revises: 29f092710449
Create Date: 2024-12-12 14:53:19.753551

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3527051d7f9b"
down_revision: Union[str, None] = "29f092710449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "municipality",
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=3067,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("short_name", sa.String(), server_default="", nullable=False),
        sa.Column(
            "name",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"fin": "", "swe": "", "eng": ""}',
            nullable=False,
        ),
        sa.Column(
            "description",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"fin": "", "swe": "", "eng": ""}',
            nullable=False,
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("parent_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["codes.municipality.id"],
            name="municipality_parent_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_municipality_level"),
        "municipality",
        ["level"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_municipality_parent_id"),
        "municipality",
        ["parent_id"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_municipality_short_name"),
        "municipality",
        ["short_name"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_municipality_value"),
        "municipality",
        ["value"],
        unique=True,
        schema="codes",
    )
    op.add_column(
        "organisation",
        sa.Column("municipality_id", sa.UUID(as_uuid=False), nullable=True),
        schema="hame",
    )
    op.create_foreign_key(
        "municipality_id_fkey",
        "organisation",
        "municipality",
        ["municipality_id"],
        ["id"],
        source_schema="hame",
        referent_schema="codes",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "municipality_id_fkey",
        "organisation",
        schema="hame",
        type_="foreignkey",
    )
    op.drop_column("organisation", "municipality_id", schema="hame")
    op.drop_index(
        op.f("ix_codes_municipality_value"),
        table_name="municipality",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_municipality_short_name"),
        table_name="municipality",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_municipality_parent_id"),
        table_name="municipality",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_municipality_level"),
        table_name="municipality",
        schema="codes",
    )
    op.drop_table("municipality", schema="codes")
    # ### end Alembic commands ###
