"""add_field_for_document_url

Revision ID: feb5395835bb
Revises: 2ea311e20eae
Create Date: 2024-06-03 14:50:37.667934

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "feb5395835bb"
down_revision: Union[str, None] = "2ea311e20eae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document", sa.Column("url", sa.String(), nullable=True), schema="hame"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "url", schema="hame")
    # ### end Alembic commands ###
