"""regulation group ordering

Revision ID: fe3e64308b9e
Revises: 5b8eb934ab21
Create Date: 2024-11-26 09:53:31.100152

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe3e64308b9e"
down_revision: Union[str, None] = "ab33a7583fd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan_regulation_group",
        sa.Column("ordering", sa.Integer(), nullable=True),
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_plan_regulation_group_ordering"),
        "plan_regulation_group",
        ["ordering"],
        unique=False,
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_hame_plan_regulation_group_ordering"),
        table_name="plan_regulation_group",
        schema="hame",
    )
    op.drop_column("plan_regulation_group", "ordering", schema="hame")
    # ### end Alembic commands ###
