"""add event date triggers

Revision ID: 4e68b614ba99
Revises: 86303e239b4d
Create Date: 2024-12-18 14:32:56.052957

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "4e68b614ba99"
down_revision: Union[str, None] = "86303e239b4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_event_date_trg_event_date_modified_at = PGTrigger(
        schema="hame",
        signature="trg_event_date_modified_at",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON event_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.create_entity(hame_event_date_trg_event_date_modified_at)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_event_date_trg_event_date_modified_at = PGTrigger(
        schema="hame",
        signature="trg_event_date_modified_at",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON event_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.drop_entity(hame_event_date_trg_event_date_modified_at)

    # ### end Alembic commands ###
