"""add plan fk to document

Revision ID: 4e8869aba78f
Revises: 9a8e55a1d1bc
Create Date: 2024-02-23 18:06:34.802480

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "4e8869aba78f"
down_revision: Union[str, None] = "9a8e55a1d1bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document", sa.Column("plan_id", sa.UUID(), nullable=False), schema="hame"
    )
    op.create_foreign_key(
        "plan_id_fkey",
        "document",
        "plan",
        ["plan_id"],
        ["id"],
        source_schema="hame",
        referent_schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("plan_id_fkey", "document", schema="hame", type_="foreignkey")
    op.drop_column("document", "plan_id", schema="hame")
    # ### end Alembic commands ###
