"""edit_plan_regulation_table

Revision ID: e22a66335242
Revises: 776ca8ea5a68
Create Date: 2024-02-15 07:51:18.528788

"""
from typing import Sequence, Union

# import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e22a66335242"
down_revision: Union[str, None] = "776ca8ea5a68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan_regulation",
        sa.Column("ordering", sa.Integer(), autoincrement=True, nullable=False),
        schema="hame",
    )
    op.alter_column(
        "plan_regulation",
        "type_of_verbal_plan_regulation_id",
        existing_type=sa.UUID(),
        nullable=True,
        schema="hame",
    )
    op.alter_column(
        "plan_regulation",
        "numeric_range",
        existing_type=postgresql.NUMRANGE(),
        nullable=True,
        schema="hame",
    )
    op.alter_column(
        "plan_regulation",
        "unit",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="hame",
    )
    op.alter_column(
        "plan_regulation",
        "numeric_value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_plan_regulation_ordering"),
        "plan_regulation",
        ["ordering"],
        unique=False,
        schema="hame",
    )
    op.drop_column("plan_regulation", "regulation_number", schema="hame")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan_regulation",
        sa.Column(
            "regulation_number", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_plan_regulation_ordering"),
        table_name="plan_regulation",
        schema="hame",
    )
    op.alter_column(
        "plan_regulation",
        "numeric_value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        schema="hame",
    )
    op.alter_column(
        "plan_regulation",
        "unit",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="hame",
    )
    op.alter_column(
        "plan_regulation",
        "numeric_range",
        existing_type=postgresql.NUMRANGE(),
        nullable=False,
        schema="hame",
    )
    op.alter_column(
        "plan_regulation",
        "type_of_verbal_plan_regulation_id",
        existing_type=sa.UUID(),
        nullable=False,
        schema="hame",
    )
    op.drop_column("plan_regulation", "ordering", schema="hame")
    # ### end Alembic commands ###
