"""add missing plan id fk

Revision ID: fa20a2e8d45e
Revises: e0e4a44290ee
Create Date: 2024-04-23 14:31:03.842257

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "fa20a2e8d45e"
down_revision: Union[str, None] = "e0e4a44290ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source_data",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        schema="hame",
    )
    op.create_foreign_key(
        "plan_id_fkey",
        "source_data",
        "plan",
        ["plan_id"],
        ["id"],
        source_schema="hame",
        referent_schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("plan_id_fkey", "source_data", schema="hame", type_="foreignkey")
    op.drop_column("source_data", "plan_id", schema="hame")
    # ### end Alembic commands ###
