"""add_triggers

Revision ID: e4fb09c07247
Revises: fa20a2e8d45e
Create Date: 2024-04-29 15:20:16.071766

"""
from typing import Sequence, Union

from alembic import op

# import sqlalchemy as sa
# import geoalchemy2
from alembic_utils.pg_function import PGFunction

# from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger

# from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "e4fb09c07247"
down_revision: Union[str, None] = "fa20a2e8d45e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_trgfunc_plan_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_plan_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_plan_modified_at)

    hame_trgfunc_land_use_area_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_land_use_area_modified_at)

    hame_trgfunc_other_area_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_other_area_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_other_area_modified_at)

    hame_trgfunc_line_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_line_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_line_modified_at)

    hame_trgfunc_land_use_point_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_point_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_land_use_point_modified_at)

    hame_trgfunc_other_point_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_other_point_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_other_point_modified_at)

    hame_trgfunc_plan_regulation_group_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_plan_regulation_group_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_plan_regulation_group_modified_at)

    hame_trgfunc_plan_regulation_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_plan_regulation_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_plan_regulation_modified_at)

    hame_trgfunc_plan_proposition_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_plan_proposition_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_plan_proposition_modified_at)

    hame_trgfunc_source_data_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_source_data_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_source_data_modified_at)

    hame_trgfunc_organisation_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_organisation_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_organisation_modified_at)

    hame_trgfunc_document_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_document_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_document_modified_at)

    hame_trgfunc_lifecycle_date_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_lifecycle_date_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_lifecycle_date_modified_at)

    hame_trgfunc_plan_new_lifecycle_date = PGFunction(
        schema="hame",
        signature="trgfunc_plan_new_lifecycle_date()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            INSERT INTO hame.lifecycle_date\n                (lifecycle_status_id, plan_id, starting_at)\n            VALUES (NEW.lifecycle_status_id, NEW.id, CURRENT_TIMESTAMP);\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_plan_new_lifecycle_date)

    hame_trgfunc_plan_regulation_new_lifecycle_date = PGFunction(
        schema="hame",
        signature="trgfunc_plan_regulation_new_lifecycle_date()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            INSERT INTO hame.lifecycle_date\n                (lifecycle_status_id, plan_regulation_id, starting_at)\n            VALUES (NEW.lifecycle_status_id, NEW.id, CURRENT_TIMESTAMP);\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_plan_regulation_new_lifecycle_date)

    hame_trgfunc_plan_proposition_new_lifecycle_date = PGFunction(
        schema="hame",
        signature="trgfunc_plan_proposition_new_lifecycle_date()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            INSERT INTO hame.lifecycle_date\n                (lifecycle_status_id, plan_proposition_id, starting_at)\n            VALUES (NEW.lifecycle_status_id, NEW.id, CURRENT_TIMESTAMP);\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_plan_proposition_new_lifecycle_date)

    hame_trgfunc_land_use_area_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.land_use_area\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_land_use_area_update_lifecycle_status)

    hame_trgfunc_other_area_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_other_area_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.other_area\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_other_area_update_lifecycle_status)

    hame_trgfunc_line_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_line_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.line\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_line_update_lifecycle_status)

    hame_trgfunc_land_use_point_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_point_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.land_use_point\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_land_use_point_update_lifecycle_status)

    hame_trgfunc_other_point_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_other_point_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.other_point\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_other_point_update_lifecycle_status)

    hame_trgfunc_plan_regulation_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_plan_regulation_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.plan_regulation\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_plan_regulation_update_lifecycle_status)

    hame_trgfunc_plan_proposition_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_plan_proposition_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.plan_proposition\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_plan_proposition_update_lifecycle_status)

    hame_trgfunc_land_use_area_add_plan_id_fkey = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_add_plan_id_fkey()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            -- Get the row with most recent created_at timestamp in plan table\n            SELECT id INTO NEW.plan_id\n            FROM hame.plan\n            ORDER BY created_at DESC\n            LIMIT 1;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_land_use_area_add_plan_id_fkey)

    hame_trgfunc_other_area_add_plan_id_fkey = PGFunction(
        schema="hame",
        signature="trgfunc_other_area_add_plan_id_fkey()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            -- Get the row with most recent created_at timestamp in plan table\n            SELECT id INTO NEW.plan_id\n            FROM hame.plan\n            ORDER BY created_at DESC\n            LIMIT 1;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_other_area_add_plan_id_fkey)

    hame_trgfunc_line_add_plan_id_fkey = PGFunction(
        schema="hame",
        signature="trgfunc_line_add_plan_id_fkey()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            -- Get the row with most recent created_at timestamp in plan table\n            SELECT id INTO NEW.plan_id\n            FROM hame.plan\n            ORDER BY created_at DESC\n            LIMIT 1;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_line_add_plan_id_fkey)

    hame_trgfunc_land_use_point_add_plan_id_fkey = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_point_add_plan_id_fkey()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            -- Get the row with most recent created_at timestamp in plan table\n            SELECT id INTO NEW.plan_id\n            FROM hame.plan\n            ORDER BY created_at DESC\n            LIMIT 1;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_land_use_point_add_plan_id_fkey)

    hame_trgfunc_other_point_add_plan_id_fkey = PGFunction(
        schema="hame",
        signature="trgfunc_other_point_add_plan_id_fkey()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            -- Get the row with most recent created_at timestamp in plan table\n            SELECT id INTO NEW.plan_id\n            FROM hame.plan\n            ORDER BY created_at DESC\n            LIMIT 1;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.create_entity(hame_trgfunc_other_point_add_plan_id_fkey)

    hame_plan_trg_plan_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_modified_at",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON plan\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_plan_modified_at()",
    )
    op.create_entity(hame_plan_trg_plan_modified_at)

    hame_land_use_area_trg_land_use_area_modified_at = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_modified_at",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON land_use_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_land_use_area_modified_at()",
    )
    op.create_entity(hame_land_use_area_trg_land_use_area_modified_at)

    hame_other_area_trg_other_area_modified_at = PGTrigger(
        schema="hame",
        signature="trg_other_area_modified_at",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON other_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_other_area_modified_at()",
    )
    op.create_entity(hame_other_area_trg_other_area_modified_at)

    hame_line_trg_line_modified_at = PGTrigger(
        schema="hame",
        signature="trg_line_modified_at",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON line\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_line_modified_at()",
    )
    op.create_entity(hame_line_trg_line_modified_at)

    hame_land_use_point_trg_land_use_point_modified_at = PGTrigger(
        schema="hame",
        signature="trg_land_use_point_modified_at",
        on_entity="hame.land_use_point",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON land_use_point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_land_use_point_modified_at()",
    )
    op.create_entity(hame_land_use_point_trg_land_use_point_modified_at)

    hame_other_point_trg_other_point_modified_at = PGTrigger(
        schema="hame",
        signature="trg_other_point_modified_at",
        on_entity="hame.other_point",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON other_point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_other_point_modified_at()",
    )
    op.create_entity(hame_other_point_trg_other_point_modified_at)

    hame_plan_regulation_group_trg_plan_regulation_group_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_group_modified_at",
        on_entity="hame.plan_regulation_group",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON plan_regulation_group\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_plan_regulation_group_modified_at()",
    )
    op.create_entity(hame_plan_regulation_group_trg_plan_regulation_group_modified_at)

    hame_plan_regulation_trg_plan_regulation_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_modified_at",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_plan_regulation_modified_at()",
    )
    op.create_entity(hame_plan_regulation_trg_plan_regulation_modified_at)

    hame_plan_proposition_trg_plan_proposition_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_modified_at",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON plan_proposition\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_plan_proposition_modified_at()",
    )
    op.create_entity(hame_plan_proposition_trg_plan_proposition_modified_at)

    hame_source_data_trg_source_data_modified_at = PGTrigger(
        schema="hame",
        signature="trg_source_data_modified_at",
        on_entity="hame.source_data",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON source_data\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_source_data_modified_at()",
    )
    op.create_entity(hame_source_data_trg_source_data_modified_at)

    hame_organisation_trg_organisation_modified_at = PGTrigger(
        schema="hame",
        signature="trg_organisation_modified_at",
        on_entity="hame.organisation",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON organisation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_organisation_modified_at()",
    )
    op.create_entity(hame_organisation_trg_organisation_modified_at)

    hame_document_trg_document_modified_at = PGTrigger(
        schema="hame",
        signature="trg_document_modified_at",
        on_entity="hame.document",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON document\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_document_modified_at()",
    )
    op.create_entity(hame_document_trg_document_modified_at)

    hame_lifecycle_date_trg_lifecycle_date_modified_at = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_modified_at",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON lifecycle_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_lifecycle_date_modified_at()",
    )
    op.create_entity(hame_lifecycle_date_trg_lifecycle_date_modified_at)

    hame_plan_trg_plan_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_new_lifecycle_date",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_plan_new_lifecycle_date()",
    )
    op.create_entity(hame_plan_trg_plan_new_lifecycle_date)

    hame_plan_regulation_trg_plan_regulation_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_new_lifecycle_date",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan_regulation\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_plan_regulation_new_lifecycle_date()",
    )
    op.create_entity(hame_plan_regulation_trg_plan_regulation_new_lifecycle_date)

    hame_plan_proposition_trg_plan_proposition_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_new_lifecycle_date",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan_proposition\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_plan_proposition_new_lifecycle_date()",
    )
    op.create_entity(hame_plan_proposition_trg_plan_proposition_new_lifecycle_date)

    hame_plan_trg_land_use_area_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_land_use_area_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_land_use_area_update_lifecycle_status)

    hame_plan_trg_other_area_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_other_area_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_other_area_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_other_area_update_lifecycle_status)

    hame_plan_trg_line_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_line_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_line_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_line_update_lifecycle_status)

    hame_plan_trg_land_use_point_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_land_use_point_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_land_use_point_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_land_use_point_update_lifecycle_status)

    hame_plan_trg_other_point_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_other_point_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_other_point_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_other_point_update_lifecycle_status)

    hame_plan_trg_plan_regulation_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_plan_regulation_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_plan_regulation_update_lifecycle_status)

    hame_plan_trg_plan_proposition_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_plan_proposition_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_plan_proposition_update_lifecycle_status)

    hame_land_use_area_trg_land_use_area_add_plan_id_fkey = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_add_plan_id_fkey",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT ON land_use_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_land_use_area_add_plan_id_fkey()",
    )
    op.create_entity(hame_land_use_area_trg_land_use_area_add_plan_id_fkey)

    hame_other_area_trg_other_area_add_plan_id_fkey = PGTrigger(
        schema="hame",
        signature="trg_other_area_add_plan_id_fkey",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE INSERT ON other_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_other_area_add_plan_id_fkey()",
    )
    op.create_entity(hame_other_area_trg_other_area_add_plan_id_fkey)

    hame_line_trg_line_add_plan_id_fkey = PGTrigger(
        schema="hame",
        signature="trg_line_add_plan_id_fkey",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE INSERT ON line\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_line_add_plan_id_fkey()",
    )
    op.create_entity(hame_line_trg_line_add_plan_id_fkey)

    hame_land_use_point_trg_land_use_point_add_plan_id_fkey = PGTrigger(
        schema="hame",
        signature="trg_land_use_point_add_plan_id_fkey",
        on_entity="hame.land_use_point",
        is_constraint=False,
        definition="BEFORE INSERT ON land_use_point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_land_use_point_add_plan_id_fkey()",
    )
    op.create_entity(hame_land_use_point_trg_land_use_point_add_plan_id_fkey)

    hame_other_point_trg_other_point_add_plan_id_fkey = PGTrigger(
        schema="hame",
        signature="trg_other_point_add_plan_id_fkey",
        on_entity="hame.other_point",
        is_constraint=False,
        definition="BEFORE INSERT ON other_point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_other_point_add_plan_id_fkey()",
    )
    op.create_entity(hame_other_point_trg_other_point_add_plan_id_fkey)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_other_point_trg_other_point_add_plan_id_fkey = PGTrigger(
        schema="hame",
        signature="trg_other_point_add_plan_id_fkey",
        on_entity="hame.other_point",
        is_constraint=False,
        definition="BEFORE INSERT ON other_point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_other_point_add_plan_id_fkey()",
    )
    op.drop_entity(hame_other_point_trg_other_point_add_plan_id_fkey)

    hame_land_use_point_trg_land_use_point_add_plan_id_fkey = PGTrigger(
        schema="hame",
        signature="trg_land_use_point_add_plan_id_fkey",
        on_entity="hame.land_use_point",
        is_constraint=False,
        definition="BEFORE INSERT ON land_use_point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_land_use_point_add_plan_id_fkey()",
    )
    op.drop_entity(hame_land_use_point_trg_land_use_point_add_plan_id_fkey)

    hame_line_trg_line_add_plan_id_fkey = PGTrigger(
        schema="hame",
        signature="trg_line_add_plan_id_fkey",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE INSERT ON line\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_line_add_plan_id_fkey()",
    )
    op.drop_entity(hame_line_trg_line_add_plan_id_fkey)

    hame_other_area_trg_other_area_add_plan_id_fkey = PGTrigger(
        schema="hame",
        signature="trg_other_area_add_plan_id_fkey",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE INSERT ON other_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_other_area_add_plan_id_fkey()",
    )
    op.drop_entity(hame_other_area_trg_other_area_add_plan_id_fkey)

    hame_land_use_area_trg_land_use_area_add_plan_id_fkey = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_add_plan_id_fkey",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT ON land_use_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_land_use_area_add_plan_id_fkey()",
    )
    op.drop_entity(hame_land_use_area_trg_land_use_area_add_plan_id_fkey)

    hame_plan_trg_plan_proposition_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_plan_proposition_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_plan_proposition_update_lifecycle_status)

    hame_plan_trg_plan_regulation_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_plan_regulation_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_plan_regulation_update_lifecycle_status)

    hame_plan_trg_other_point_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_other_point_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_other_point_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_other_point_update_lifecycle_status)

    hame_plan_trg_land_use_point_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_land_use_point_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_land_use_point_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_land_use_point_update_lifecycle_status)

    hame_plan_trg_line_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_line_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_line_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_line_update_lifecycle_status)

    hame_plan_trg_other_area_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_other_area_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_other_area_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_other_area_update_lifecycle_status)

    hame_plan_trg_land_use_area_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_land_use_area_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_land_use_area_update_lifecycle_status)

    hame_plan_proposition_trg_plan_proposition_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_new_lifecycle_date",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan_proposition\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_plan_proposition_new_lifecycle_date()",
    )
    op.drop_entity(hame_plan_proposition_trg_plan_proposition_new_lifecycle_date)

    hame_plan_regulation_trg_plan_regulation_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_new_lifecycle_date",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan_regulation\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_plan_regulation_new_lifecycle_date()",
    )
    op.drop_entity(hame_plan_regulation_trg_plan_regulation_new_lifecycle_date)

    hame_plan_trg_plan_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_new_lifecycle_date",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON plan\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id <> OLD.lifecycle_status_id)\n        EXECUTE FUNCTION hame.trgfunc_plan_new_lifecycle_date()",
    )
    op.drop_entity(hame_plan_trg_plan_new_lifecycle_date)

    hame_lifecycle_date_trg_lifecycle_date_modified_at = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_modified_at",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON lifecycle_date\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_lifecycle_date_modified_at()",
    )
    op.drop_entity(hame_lifecycle_date_trg_lifecycle_date_modified_at)

    hame_document_trg_document_modified_at = PGTrigger(
        schema="hame",
        signature="trg_document_modified_at",
        on_entity="hame.document",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON document\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_document_modified_at()",
    )
    op.drop_entity(hame_document_trg_document_modified_at)

    hame_organisation_trg_organisation_modified_at = PGTrigger(
        schema="hame",
        signature="trg_organisation_modified_at",
        on_entity="hame.organisation",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON organisation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_organisation_modified_at()",
    )
    op.drop_entity(hame_organisation_trg_organisation_modified_at)

    hame_source_data_trg_source_data_modified_at = PGTrigger(
        schema="hame",
        signature="trg_source_data_modified_at",
        on_entity="hame.source_data",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON source_data\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_source_data_modified_at()",
    )
    op.drop_entity(hame_source_data_trg_source_data_modified_at)

    hame_plan_proposition_trg_plan_proposition_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_modified_at",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON plan_proposition\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_plan_proposition_modified_at()",
    )
    op.drop_entity(hame_plan_proposition_trg_plan_proposition_modified_at)

    hame_plan_regulation_trg_plan_regulation_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_modified_at",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON plan_regulation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_plan_regulation_modified_at()",
    )
    op.drop_entity(hame_plan_regulation_trg_plan_regulation_modified_at)

    hame_plan_regulation_group_trg_plan_regulation_group_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_group_modified_at",
        on_entity="hame.plan_regulation_group",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON plan_regulation_group\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_plan_regulation_group_modified_at()",
    )
    op.drop_entity(hame_plan_regulation_group_trg_plan_regulation_group_modified_at)

    hame_other_point_trg_other_point_modified_at = PGTrigger(
        schema="hame",
        signature="trg_other_point_modified_at",
        on_entity="hame.other_point",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON other_point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_other_point_modified_at()",
    )
    op.drop_entity(hame_other_point_trg_other_point_modified_at)

    hame_land_use_point_trg_land_use_point_modified_at = PGTrigger(
        schema="hame",
        signature="trg_land_use_point_modified_at",
        on_entity="hame.land_use_point",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON land_use_point\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_land_use_point_modified_at()",
    )
    op.drop_entity(hame_land_use_point_trg_land_use_point_modified_at)

    hame_line_trg_line_modified_at = PGTrigger(
        schema="hame",
        signature="trg_line_modified_at",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON line\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_line_modified_at()",
    )
    op.drop_entity(hame_line_trg_line_modified_at)

    hame_other_area_trg_other_area_modified_at = PGTrigger(
        schema="hame",
        signature="trg_other_area_modified_at",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON other_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_other_area_modified_at()",
    )
    op.drop_entity(hame_other_area_trg_other_area_modified_at)

    hame_land_use_area_trg_land_use_area_modified_at = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_modified_at",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON land_use_area\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_land_use_area_modified_at()",
    )
    op.drop_entity(hame_land_use_area_trg_land_use_area_modified_at)

    hame_plan_trg_plan_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_modified_at",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON plan\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_plan_modified_at()",
    )
    op.drop_entity(hame_plan_trg_plan_modified_at)

    hame_trgfunc_other_point_add_plan_id_fkey = PGFunction(
        schema="hame",
        signature="trgfunc_other_point_add_plan_id_fkey()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            -- Get the row with most recent created_at timestamp in plan table\n            SELECT id INTO NEW.plan_id\n            FROM hame.plan\n            ORDER BY created_at DESC\n            LIMIT 1;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_other_point_add_plan_id_fkey)

    hame_trgfunc_land_use_point_add_plan_id_fkey = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_point_add_plan_id_fkey()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            -- Get the row with most recent created_at timestamp in plan table\n            SELECT id INTO NEW.plan_id\n            FROM hame.plan\n            ORDER BY created_at DESC\n            LIMIT 1;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_land_use_point_add_plan_id_fkey)

    hame_trgfunc_line_add_plan_id_fkey = PGFunction(
        schema="hame",
        signature="trgfunc_line_add_plan_id_fkey()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            -- Get the row with most recent created_at timestamp in plan table\n            SELECT id INTO NEW.plan_id\n            FROM hame.plan\n            ORDER BY created_at DESC\n            LIMIT 1;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_line_add_plan_id_fkey)

    hame_trgfunc_other_area_add_plan_id_fkey = PGFunction(
        schema="hame",
        signature="trgfunc_other_area_add_plan_id_fkey()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            -- Get the row with most recent created_at timestamp in plan table\n            SELECT id INTO NEW.plan_id\n            FROM hame.plan\n            ORDER BY created_at DESC\n            LIMIT 1;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_other_area_add_plan_id_fkey)

    hame_trgfunc_land_use_area_add_plan_id_fkey = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_add_plan_id_fkey()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            -- Get the row with most recent created_at timestamp in plan table\n            SELECT id INTO NEW.plan_id\n            FROM hame.plan\n            ORDER BY created_at DESC\n            LIMIT 1;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_land_use_area_add_plan_id_fkey)

    hame_trgfunc_plan_proposition_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_plan_proposition_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.plan_proposition\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_plan_proposition_update_lifecycle_status)

    hame_trgfunc_plan_regulation_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_plan_regulation_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.plan_regulation\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_plan_regulation_update_lifecycle_status)

    hame_trgfunc_other_point_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_other_point_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.other_point\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_other_point_update_lifecycle_status)

    hame_trgfunc_land_use_point_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_point_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.land_use_point\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_land_use_point_update_lifecycle_status)

    hame_trgfunc_line_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_line_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.line\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_line_update_lifecycle_status)

    hame_trgfunc_other_area_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_other_area_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.other_area\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_other_area_update_lifecycle_status)

    hame_trgfunc_land_use_area_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_update_lifecycle_status()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            UPDATE hame.land_use_area\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE plan_regulation_group_id = NEW.plan_regulation_group_id;\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_land_use_area_update_lifecycle_status)

    hame_trgfunc_plan_proposition_new_lifecycle_date = PGFunction(
        schema="hame",
        signature="trgfunc_plan_proposition_new_lifecycle_date()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            INSERT INTO hame.lifecycle_date\n                (lifecycle_status_id, plan_proposition_id, starting_at)\n            VALUES (NEW.lifecycle_status_id, NEW.id, CURRENT_TIMESTAMP);\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_plan_proposition_new_lifecycle_date)

    hame_trgfunc_plan_regulation_new_lifecycle_date = PGFunction(
        schema="hame",
        signature="trgfunc_plan_regulation_new_lifecycle_date()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            INSERT INTO hame.lifecycle_date\n                (lifecycle_status_id, plan_regulation_id, starting_at)\n            VALUES (NEW.lifecycle_status_id, NEW.id, CURRENT_TIMESTAMP);\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_plan_regulation_new_lifecycle_date)

    hame_trgfunc_plan_new_lifecycle_date = PGFunction(
        schema="hame",
        signature="trgfunc_plan_new_lifecycle_date()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            INSERT INTO hame.lifecycle_date\n                (lifecycle_status_id, plan_id, starting_at)\n            VALUES (NEW.lifecycle_status_id, NEW.id, CURRENT_TIMESTAMP);\n            RETURN NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_plan_new_lifecycle_date)

    hame_trgfunc_lifecycle_date_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_lifecycle_date_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_lifecycle_date_modified_at)

    hame_trgfunc_document_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_document_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_document_modified_at)

    hame_trgfunc_organisation_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_organisation_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_organisation_modified_at)

    hame_trgfunc_source_data_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_source_data_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_source_data_modified_at)

    hame_trgfunc_plan_proposition_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_plan_proposition_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_plan_proposition_modified_at)

    hame_trgfunc_plan_regulation_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_plan_regulation_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_plan_regulation_modified_at)

    hame_trgfunc_plan_regulation_group_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_plan_regulation_group_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_plan_regulation_group_modified_at)

    hame_trgfunc_other_point_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_other_point_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_other_point_modified_at)

    hame_trgfunc_land_use_point_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_point_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_land_use_point_modified_at)

    hame_trgfunc_line_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_line_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_line_modified_at)

    hame_trgfunc_other_area_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_other_area_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_other_area_modified_at)

    hame_trgfunc_land_use_area_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_land_use_area_modified_at)

    hame_trgfunc_plan_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_plan_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.drop_entity(hame_trgfunc_plan_modified_at)

    # ### end Alembic commands ###
