"""add regions code table

Revision ID: ad29908c50ad
Revises: 4e8869aba78f
Create Date: 2024-02-26 14:33:34.556951

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ad29908c50ad"
down_revision: Union[str, None] = "4e8869aba78f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "administrative_region",
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("short_name", sa.String(), server_default="", nullable=False),
        sa.Column(
            "name",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"fin": "", "swe": "", "eng": ""}',
            nullable=False,
        ),
        sa.Column(
            "description",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"fin": "", "swe": "", "eng": ""}',
            nullable=False,
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["codes.administrative_region.id"],
            name="administrative_region_parent_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_administrative_region_level"),
        "administrative_region",
        ["level"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_administrative_region_parent_id"),
        "administrative_region",
        ["parent_id"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_administrative_region_short_name"),
        "administrative_region",
        ["short_name"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_administrative_region_value"),
        "administrative_region",
        ["value"],
        unique=True,
        schema="codes",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_codes_administrative_region_value"),
        table_name="administrative_region",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_administrative_region_short_name"),
        table_name="administrative_region",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_administrative_region_parent_id"),
        table_name="administrative_region",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_administrative_region_level"),
        table_name="administrative_region",
        schema="codes",
    )
    op.drop_table("administrative_region", schema="codes")
    # ### end Alembic commands ###
