"""add validation fields for plan

Revision ID: dea8681d5134
Revises: a09325981a78
Create Date: 2024-04-18 14:53:42.056548

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dea8681d5134"
down_revision: Union[str, None] = "4f8bcdc437a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan",
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan",
        sa.Column(
            "validation_errors",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan", "validation_errors", schema="hame")
    op.drop_column("plan", "validated_at", schema="hame")
    # ### end Alembic commands ###
