"""add parent to code

Revision ID: 13819c34faf2
Revises: 63cb1b0cf3be
Create Date: 2024-01-31 17:50:17.757822

"""
from typing import Sequence, Union

# import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13819c34faf2"
down_revision: Union[str, None] = "63cb1b0cf3be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lifecycle_status",
        sa.Column("level", sa.Integer(), server_default="0", nullable=False),
        schema="codes",
    )
    op.add_column(
        "lifecycle_status",
        sa.Column("parent_id", sa.UUID(), nullable=True),
        schema="codes",
    )
    op.create_foreign_key(
        "lifecycle_status_parent_id_fkey",
        "lifecycle_status",
        "lifecycle_status",
        ["parent_id"],
        ["id"],
        source_schema="codes",
        referent_schema="codes",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "lifecycle_status_parent_id_fkey",
        "lifecycle_status",
        schema="codes",
        type_="foreignkey",
    )
    op.drop_column("lifecycle_status", "parent_id", schema="codes")
    op.drop_column("lifecycle_status", "level", schema="codes")
    # ### end Alembic commands ###
