"""add_category_of_publicity_codelist_into_document_table

Revision ID: 2ea311e20eae
Revises: dba7f323b644
Create Date: 2024-06-03 14:27:11.766147

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ea311e20eae"
down_revision: Union[str, None] = "dba7f323b644"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("category_of_publicity_id", sa.UUID(as_uuid=False), nullable=False),
        schema="hame",
    )
    op.create_foreign_key(
        "category_of_publicity_id_fkey",
        "document",
        "category_of_publicity",
        ["category_of_publicity_id"],
        ["id"],
        source_schema="hame",
        referent_schema="codes",
    )
    op.drop_column("document", "publicity", schema="hame")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column(
            "publicity",
            sa.VARCHAR(length=11),
            autoincrement=False,
            nullable=False,
        ),
        schema="hame",
    )
    op.drop_constraint(
        "category_of_publicity_id_fkey",
        "document",
        schema="hame",
        type_="foreignkey",
    )
    op.drop_column("document", "category_of_publicity_id", schema="hame")
    # ### end Alembic commands ###
