"""short name uniqueness fix

Revision ID: e9a045c08304
Revises: 09f44e0e7110
Create Date: 2024-12-02 13:54:23.903091

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9a045c08304"
down_revision: Union[str, None] = "09f44e0e7110"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plan_regulation_group",
        "short_name",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="hame",
    )
    op.drop_index(
        "ix_hame_plan_regulation_group_short_name",
        table_name="plan_regulation_group",
        schema="hame",
    )
    op.create_index(
        "ix_plan_regulation_group_plan_id_short_name",
        "plan_regulation_group",
        ["plan_id", "short_name"],
        unique=True,
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_plan_regulation_group_plan_id_short_name",
        table_name="plan_regulation_group",
        schema="hame",
    )
    op.create_index(
        "ix_hame_plan_regulation_group_short_name",
        "plan_regulation_group",
        ["short_name"],
        unique=True,
        schema="hame",
    )
    op.alter_column(
        "plan_regulation_group",
        "short_name",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="hame",
    )
    # ### end Alembic commands ###
