"""make plan type not nullable

Revision ID: 0da11d97b6cb
Revises: dea8681d5134
Create Date: 2024-04-24 15:10:01.131136

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "0da11d97b6cb"
down_revision: Union[str, None] = "dea8681d5134"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plan",
        "plan_type_id",
        existing_type=sa.UUID(),
        nullable=False,
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plan",
        "plan_type_id",
        existing_type=sa.UUID(),
        nullable=True,
        schema="hame",
    )
    # ### end Alembic commands ###
