"""add plan theme code list

Revision ID: e0e4a44290ee
Revises: ee5a32df4531
Create Date: 2024-03-28 16:22:45.917125

"""
from typing import Sequence, Union

# import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e0e4a44290ee"
down_revision: Union[str, None] = "ee5a32df4531"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_theme",
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("short_name", sa.String(), server_default="", nullable=False),
        sa.Column(
            "name",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"fin": "", "swe": "", "eng": ""}',
            nullable=False,
        ),
        sa.Column(
            "description",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"fin": "", "swe": "", "eng": ""}',
            nullable=False,
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["codes.plan_theme.id"],
            name="plan_theme_parent_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_plan_theme_level"),
        "plan_theme",
        ["level"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_plan_theme_parent_id"),
        "plan_theme",
        ["parent_id"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_plan_theme_short_name"),
        "plan_theme",
        ["short_name"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_plan_theme_value"),
        "plan_theme",
        ["value"],
        unique=True,
        schema="codes",
    )
    op.add_column(
        "plan_proposition",
        sa.Column("plan_theme_id", sa.UUID(), nullable=True),
        schema="hame",
    )
    op.create_foreign_key(
        "plan_theme_id_fkey",
        "plan_proposition",
        "plan_theme",
        ["plan_theme_id"],
        ["id"],
        source_schema="hame",
        referent_schema="codes",
    )
    op.add_column(
        "plan_regulation",
        sa.Column("plan_theme_id", sa.UUID(), nullable=True),
        schema="hame",
    )
    op.create_foreign_key(
        "plan_theme_id_fkey",
        "plan_regulation",
        "plan_theme",
        ["plan_theme_id"],
        ["id"],
        source_schema="hame",
        referent_schema="codes",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "plan_theme_id_fkey",
        "plan_regulation",
        schema="hame",
        type_="foreignkey",
    )
    op.drop_column("plan_regulation", "plan_theme_id", schema="hame")
    op.drop_constraint(
        "plan_theme_id_fkey",
        "plan_proposition",
        schema="hame",
        type_="foreignkey",
    )
    op.drop_column("plan_proposition", "plan_theme_id", schema="hame")
    op.drop_index(
        op.f("ix_codes_plan_theme_value"),
        table_name="plan_theme",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_plan_theme_short_name"),
        table_name="plan_theme",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_plan_theme_parent_id"),
        table_name="plan_theme",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_plan_theme_level"),
        table_name="plan_theme",
        schema="codes",
    )
    op.drop_table("plan_theme", schema="codes")
    # ### end Alembic commands ###
