"""separate range fields

Revision ID: d7a23c8273dc
Revises: 8b6f3fb9c92e
Create Date: 2025-01-22 15:33:46.390311

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7a23c8273dc"
down_revision: Union[str, None] = "8b6f3fb9c92e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "land_use_area",
        sa.Column("height_min", sa.Float(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "land_use_area",
        sa.Column("height_max", sa.Float(), nullable=True),
        schema="hame",
    )
    op.drop_column("land_use_area", "height_range", schema="hame")
    op.add_column(
        "land_use_point",
        sa.Column("height_min", sa.Float(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "land_use_point",
        sa.Column("height_max", sa.Float(), nullable=True),
        schema="hame",
    )
    op.drop_column("land_use_point", "height_range", schema="hame")
    op.add_column(
        "line",
        sa.Column("height_min", sa.Float(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "line",
        sa.Column("height_max", sa.Float(), nullable=True),
        schema="hame",
    )
    op.drop_column("line", "height_range", schema="hame")
    op.add_column(
        "other_area",
        sa.Column("height_min", sa.Float(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "other_area",
        sa.Column("height_max", sa.Float(), nullable=True),
        schema="hame",
    )
    op.drop_column("other_area", "height_range", schema="hame")
    op.add_column(
        "other_point",
        sa.Column("height_min", sa.Float(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "other_point",
        sa.Column("height_max", sa.Float(), nullable=True),
        schema="hame",
    )
    op.drop_column("other_point", "height_range", schema="hame")
    op.add_column(
        "plan_regulation",
        sa.Column("numeric_range_min", sa.Integer(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_regulation",
        sa.Column("numeric_range_max", sa.Integer(), nullable=True),
        schema="hame",
    )
    op.drop_column("plan_regulation", "numeric_range", schema="hame")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan_regulation",
        sa.Column(
            "numeric_range",
            postgresql.NUMRANGE(),
            autoincrement=False,
            nullable=True,
        ),
        schema="hame",
    )
    op.drop_column("plan_regulation", "numeric_range_max", schema="hame")
    op.drop_column("plan_regulation", "numeric_range_min", schema="hame")
    op.add_column(
        "other_point",
        sa.Column(
            "height_range",
            postgresql.NUMRANGE(),
            autoincrement=False,
            nullable=True,
        ),
        schema="hame",
    )
    op.drop_column("other_point", "height_max", schema="hame")
    op.drop_column("other_point", "height_min", schema="hame")
    op.add_column(
        "other_area",
        sa.Column(
            "height_range",
            postgresql.NUMRANGE(),
            autoincrement=False,
            nullable=True,
        ),
        schema="hame",
    )
    op.drop_column("other_area", "height_max", schema="hame")
    op.drop_column("other_area", "height_min", schema="hame")
    op.add_column(
        "line",
        sa.Column(
            "height_range",
            postgresql.NUMRANGE(),
            autoincrement=False,
            nullable=True,
        ),
        schema="hame",
    )
    op.drop_column("line", "height_max", schema="hame")
    op.drop_column("line", "height_min", schema="hame")
    op.add_column(
        "land_use_point",
        sa.Column(
            "height_range",
            postgresql.NUMRANGE(),
            autoincrement=False,
            nullable=True,
        ),
        schema="hame",
    )
    op.drop_column("land_use_point", "height_max", schema="hame")
    op.drop_column("land_use_point", "height_min", schema="hame")
    op.add_column(
        "land_use_area",
        sa.Column(
            "height_range",
            postgresql.NUMRANGE(),
            autoincrement=False,
            nullable=True,
        ),
        schema="hame",
    )
    op.drop_column("land_use_area", "height_max", schema="hame")
    op.drop_column("land_use_area", "height_min", schema="hame")
    # ### end Alembic commands ###
