"""add subject identifiers

Revision ID: 265a8e71161c
Revises: a335654a069a
Create Date: 2025-01-24 17:10:25.892137

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "265a8e71161c"
down_revision: Union[str, None] = "a335654a069a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan_regulation",
        sa.Column("subject_identifiers", sa.ARRAY(sa.TEXT()), nullable=True),
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan_regulation", "subject_identifiers", schema="hame")
    # ### end Alembic commands ###
