"""Remove cascade del on a code table

Revision ID: 08c795658444
Revises: b1f6c870e220
Create Date: 2025-02-19 09:00:29.688004

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08c795658444"
down_revision: Union[str, None] = "b1f6c870e220"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "plan_lifecycle_status_id_fkey",
        "lifecycle_date",
        schema="hame",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "plan_lifecycle_status_id_fkey",
        "lifecycle_date",
        "lifecycle_status",
        ["lifecycle_status_id"],
        ["id"],
        source_schema="hame",
        referent_schema="codes",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "plan_lifecycle_status_id_fkey",
        "lifecycle_date",
        schema="hame",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "plan_lifecycle_status_id_fkey",
        "lifecycle_date",
        "lifecycle_status",
        ["lifecycle_status_id"],
        ["id"],
        source_schema="hame",
        referent_schema="codes",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
