"""additional information triggers

Revision ID: 70e48d7ed252
Revises: 6d26d0c16716
Create Date: 2025-01-27 14:31:29.261100

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "70e48d7ed252"
down_revision: Union[str, None] = "6d26d0c16716"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_additional_information_trg_additional_information_modified_at = PGTrigger(
        schema="hame",
        signature="trg_additional_information_modified_at",
        on_entity="hame.additional_information",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON additional_information\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.create_entity(hame_additional_information_trg_additional_information_modified_at)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_additional_information_trg_additional_information_modified_at = PGTrigger(
        schema="hame",
        signature="trg_additional_information_modified_at",
        on_entity="hame.additional_information",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON additional_information\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.drop_entity(hame_additional_information_trg_additional_information_modified_at)

    # ### end Alembic commands ###
