"""cascade delete additional information

Revision ID: f90eb601dceb
Revises: 74c313df967b
Create Date: 2025-02-19 12:01:27.426582

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f90eb601dceb"
down_revision: Union[str, None] = "74c313df967b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "plan_regulation_id_fkey",
        "additional_information",
        schema="hame",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "plan_regulation_id_fkey",
        "additional_information",
        "plan_regulation",
        ["plan_regulation_id"],
        ["id"],
        source_schema="hame",
        referent_schema="hame",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "plan_regulation_id_fkey",
        "additional_information",
        schema="hame",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "plan_regulation_id_fkey",
        "additional_information",
        "plan_regulation",
        ["plan_regulation_id"],
        ["id"],
        source_schema="hame",
        referent_schema="hame",
    )
    # ### end Alembic commands ###
